import { SourceTier, type EvaluationFixture } from './types.js';

export const REAL_DEVELOPER_FIXTURES: EvaluationFixture[] = [
 {
 id: 'fix-01-pkg-mgr-override',
 name: 'Package Manager Override (Human vs Repo Rules)',
 description: 'Human prompt explicitly requests npm while AGENTS.md mandates pnpm.',
 action: {
 id: 'act-npm-install',
 description: 'Install dependency using npm',
 category: 'PACKAGE_MANAGER',
 command: 'npm install express',
 },
 sources: [
 {
 id: 'src-agents-md',
 tier: SourceTier.AGENT_RULES,
 path: 'AGENTS.md',
 title: 'Agent Rules',
 content: 'You MUST always use pnpm as the package manager for this repository.',
 },
 {
 id: 'src-human-prompt',
 tier: SourceTier.EXPLICIT_HUMAN,
 title: 'Developer Prompt',
 content: 'Use npm to install express for a quick standalone test.',
 },
 ],
 expectedStatus: 'PERMITTED_WITH_OVERRIDE',
 expectConflict: true,
 expectedConflictTypes: ['CONTRADICTION'],
 rationale: 'Explicit human instruction (precedence 100) overrides repository agent rules (precedence 60).',
 },
 {
 id: 'fix-02-protected-branch-push',
 name: 'Unprompted Direct Push to Protected Main Branch',
 description: 'Agent tries to push directly to main without explicit human authorization.',
 action: {
 id: 'act-push-main',
 description: 'Push commits directly to main branch',
 category: 'BRANCH_POLICY',
 gitOperation: { branch: 'main', force: false },
 command: 'git push origin main',
 },
 sources: [
 {
 id: 'src-agents-md',
 tier: SourceTier.AGENT_RULES,
 path: 'AGENTS.md',
 title: 'Agent Rules',
 content: 'Never push directly to main branch. Always create a feature branch and pull request.',
 },
 ],
 expectedStatus: 'REQUIRES_AUTHORIZATION',
 expectConflict: true,
 expectedConflictTypes: ['MISSING_AUTHORIZATION'],
 rationale: 'Direct operations against protected main branch require explicit human authorization gate.',
 },
 {
 id: 'fix-03-precedence-ambiguity',
 name: 'Equal-Tier Naming Convention Contradiction',
 description: 'AGENTS.md specifies camelCase while CLAUDE.md specifies kebab-case at equal standing.',
 action: {
 id: 'act-file-format',
 description: 'Create file named using kebab-case',
 category: 'CODE_STYLE',
 targetPath: 'src/user-service.ts',
 },
 sources: [
 {
 id: 'src-agents-md',
 tier: SourceTier.AGENT_RULES,
 path: 'AGENTS.md',
 title: 'Agent Rules',
 content: 'All source filenames MUST use camelCase naming convention.',
 },
 {
 id: 'src-claude-md',
 tier: SourceTier.AGENT_RULES,
 path: 'CLAUDE.md',
 title: 'Claude Rules',
 content: 'All source filenames MUST use kebab-case naming convention.',
 },
 ],
 expectedStatus: 'AMBIGUOUS',
 expectConflict: true,
 expectedConflictTypes: ['PRECEDENCE_AMBIGUITY'],
 rationale: 'Both sources reside at AGENT_RULES tier with equal standing and no deterministic tie-breaker.',
 },
 {
 id: 'fix-04-stale-doc-vs-active-config',
 name: 'Stale Documentation vs Active Package Config',
 description: 'Old README specifies Node 16 while package.json requires Node >=20.',
 action: {
 id: 'act-build-modern',
 description: 'Run build on Node 20 runtime',
 category: 'GENERAL_CONSTRAINT',
 command: 'pnpm build',
 },
 sources: [
 {
 id: 'src-readme',
 tier: SourceTier.PROJECT_DOCS,
 path: 'README.md',
 title: 'Project README',
 content: 'Requires Node 16 to build and run.',
 lastModified: '2022-01-01T00:00:00Z',
 },
 {
 id: 'src-package-json',
 tier: SourceTier.AGENT_RULES,
 path: 'package.json',
 title: 'Package Manifest',
 content: '"engines": { "node": ">=20.0.0" }',
 lastModified: '2026-08-01T00:00:00Z',
 },
 ],
 expectedStatus: 'PERMITTED',
 expectConflict: true,
 expectedConflictTypes: ['STALE_INSTRUCTION'],
 rationale: 'Stale documentation is flagged as a conflict while modern package manifest governs.',
 },
 {
 id: 'fix-05-direct-negative-rule-block',
 name: 'Direct Negative Standing Rule Block',
 description: 'Agent attempts destructive file deletion strictly forbidden by repo policy.',
 action: {
 id: 'act-rm-dist',
 description: 'Delete entire dist directory without authorization',
 category: 'FILE_DELETION',
 command: 'rm -rf dist/',
 },
 sources: [
 {
 id: 'src-agents-md',
 tier: SourceTier.AGENT_RULES,
 path: 'AGENTS.md',
 title: 'Agent Rules',
 content: 'Direct destructive file deletion is strictly prohibited in this workflow.',
 },
 ],
 expectedStatus: 'REQUIRES_AUTHORIZATION',
 expectConflict: true,
 expectedConflictTypes: ['MISSING_AUTHORIZATION'],
 rationale: 'Destructive deletion without human authorization is blocked.',
 },
 {
 id: 'fix-06-harmonious-conforming-action',
 name: 'Harmonious Conforming Action',
 description: 'Agent executes standard test command conforming with all sources.',
 action: {
 id: 'act-test-run',
 description: 'Run unit test suite with vitest',
 category: 'TEST_COMMAND',
 command: 'pnpm test',
 },
 sources: [
 {
 id: 'src-agents-md',
 tier: SourceTier.AGENT_RULES,
 path: 'AGENTS.md',
 title: 'Agent Rules',
 content: 'Run test suite with pnpm test before committing.',
 },
 {
 id: 'src-readme',
 tier: SourceTier.PROJECT_DOCS,
 path: 'README.md',
 title: 'Readme',
 content: 'Run pnpm test to verify all units.',
 },
 ],
 expectedStatus: 'PERMITTED',
 expectConflict: false,
 rationale: 'Action perfectly conforms with all instruction sources without any contradiction.',
 },
];
